strictness: medium
autodetect: yes

ignore-paths:
  - thug/Analysis/peepdf/
  - thug/Logging/modules/MITRE/__init__.py
  - thug/Logging/modules/MITRE/MAEC_v1_1.py
  - thug/Logging/modules/MITRE/MAEC_v4_0.py
  - utils/
  - tools/
  - hpfeeds/
  - samples/steps/exploits.py
  - samples/steps/misc.py
  - thug/ThugAPI/IThugAPI.py
  - thug/ThugAPI/__init__.py
  - thug/Plugins/IPlugin.py
  - thug/ActiveX/modules/MSXML2DOMDocument.py
  - ez_setup.py

pylint:
  disable:
    - too-many-arguments
    - too-many-locals
    - too-many-statements
    - too-many-branches
    - unused-argument
    - protected-access
    - unnecessary-lambda
    - line-too-long

pyflakes:
  disable:
    - F841

pep8:
  disable:
    # E116 - Unexpected indent for comment
    - E116
    # E501 - Line too long
    - E501

mccabe:
  disable:
    - MC0001
