include "urlclassifier/blackhole.yar"
include "urlclassifier/cool.yar"
include "urlclassifier/redkit.yar"
include "urlclassifier/styx.yar"
include "urlclassifier/sweetorange.yar"
include "urlclassifier/tds.yar"
